version: '3.8'

services:

  mongo:
    image: mongo:4.4.6
    container_name: mon_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data_mongo:/data/db
    command: --bind_ip_all


  scraper:
    build: .
    container_name: mon_scraper
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - PYTHONPATH=/app/scrappy/crawler
    command: sh -c "while true; do echo 'Lancement du Scraper...' && cd /app/scrappy/crawler && scrapy runspider paruvendu_spider.py && echo 'Pause de 5 minutes...' && sleep 300; done"

  webapp:
    build: .
    container_name: mon_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - .:/app
    command: streamlit run Webapp/home.py --server.port=8501 --server.address=0.0.0.0