version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mon_mongo
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - scraping_network

  scraper:
    build: . 
    container_name: mon_scraper
    depends_on:
      - mongo 
    networks:
      - scraping_network
networks:
  scraping_network:
    driver: bridge